# Define two scrapers
#   1. docker - which collects the matrixes of docker
#   2. eexporter - which collects the matrixes of elasticsearch
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'lambda-monitor'
scrape_configs:
  - job_name: 'elastic-search-exporter'
    target_groups:
      - targets: ['172.17.0.1:9114']
